Adds new integration [alryaz/hass-tns-energo]
hacs/default pull request #1033
Opened 2021-07-29 12:04 UTC by alryaz

2021-07-29 19:10 UTC, jbouwh requested changes
There is still a TODO in README.md
https://github.com/alryaz/hass-tns-energo#readme
Please complete documentation.
Is there a short English description available?

2021-07-30 08:04 UTC, alryaz commented
Alright, will deal with TODO's today.

To be honest, this addon is almost exclusive to Russian users; however, I think, a little English description wouldn't hurt.
(In short, this is an energy website adapter)

2021-07-30 09:44 UTC, alryaz commented
Removed that `@TODO@` entry, added a few screenshots and an English preamable.

I'd love to add more English README's, but since most of my components are oriented around adapting personal cabinets to HA, and there are so many similarities between them (service calls, attributes, etc.), I'm working on a README generator based on their traits. Not yet done, but README will be blooming with data when it's done.

2021-07-30 09:58 UTC, jbouwh approved these changes

2021-08-15 10:22 UTC, merged