adding pgnig sensor
hacs/default pull request #1256
Opened 2022-02-19 23:10 UTC by pawelhulek

2022-02-20 17:49 UTC, ludeeus requested changes
CI does not pass. <https://hacs.xyz/docs/publish/include#before-submitting>

2022-02-21 17:01 UTC, pawelhulek commented
/recheck

2022-02-21 17:06 UTC, pawelhulek commented
/recheck

2022-02-27 18:08 UTC, pawelhulek commented
https://github.com/home-assistant/brands/pull/3212 here is brands MR

2022-02-28 07:51 UTC, pawelhulek commented
/recheck

2022-02-28 19:44 UTC, pawelhulek commented
/recheck

2022-02-28 19:44 UTC, pawelhulek commented
/recheck

2022-02-28 20:03 UTC, pawelhulek commented
/recheck

2022-02-28 20:23 UTC, pawelhulek commented
/recheck

2022-03-05 15:49 UTC, merged