Adds new integration [speleolontra/daikin_residential_altherma]
hacs/default pull request #1799
Opened 2023-03-16 07:20 UTC by jwillemsen

## Checklist

- [X] I've read the [publishing documentation](https://hacs.xyz/docs/publish/start).
- [X] I've added the [HACS action](https://hacs.xyz/docs/publish/action) to my repository.
- [X] (For integrations only) I've added the [hassfest action](https://developers.home-assistant.io/blog/2020/04/16/hassfest/) to my repository.
- [X] The actions are passing without any disabled checks in my repository.
- [X] I've added a link to the action run on my repository below in the links section.
- [X] I've created a new release of the repository after the validation actions were run successfully.

## Links

Link to current release: https://github.com/speleolontra/daikin_residential_altherma/releases/tag/v2.5.2
Link to successful HACS action (without the `ignore` key): https://github.com/speleolontra/daikin_residential_altherma/actions/runs/4434522345/jobs/7780590158
Link to successful hassfest action (if integration): https://github.com/speleolontra/daikin_residential_altherma/actions/runs/4434522725

2023-10-01 12:12 UTC, ludeeus requested changes
CI failing

2023-10-03 08:28 UTC, jwillemsen commented
Thanks @ludeeus, looks hassfest got stricter after I made this PR, where can I find documentation about this error, looks I have to add some translation for a service.

2023-10-03 08:30 UTC, ludeeus commented
It's probably on HA dev docs or HA discord.

2023-10-03 08:39 UTC, jwillemsen commented
Ok, fixed as far as the CI on the integration itself shows.

2023-10-08 13:25 UTC, merged