Adds new plugin [zanac/temperature-heatmap-card]
hacs/default pull request #2045
Opened 2023-08-31 06:16 UTC by zanac

## Checklist

- [x] I've read the [publishing documentation](https://hacs.xyz/docs/publish/start).
- [x] I've added the [HACS action](https://hacs.xyz/docs/publish/action) to my repository.
- [ ] (For integrations only) I've added the [hassfest action](https://developers.home-assistant.io/blog/2020/04/16/hassfest/) to my repository.
- [x] The actions are passing without any disabled checks in my repository.
- [x] I've added a link to the action run on my repository below in the links section.
- [x] I've created a new release of the repository after the validation actions were run successfully.

## Links

Link to current release: https://github.com/zanac/temperature-heatmap-card/releases/tag/v0.9.2
Link to successful HACS action (without the ignore key): https://github.com/zanac/temperature-heatmap-card/actions/runs/5885227755
Link to successful hassfest action (if integration): <N/A>

2023-12-03 20:09 UTC, ludeeus requested changes

2023-12-03 20:09 UTC, ludeeus commented on plugin
> +  "zanac/temperature-heatmap-card",
<img width="743" alt="2023-12-03_21-09-14" src="https://github.com/hacs/default/assets/15093472/588395f8-3e18-409c-bbf6-bc4d178fac06">
It cannot be updated.

2023-12-04 15:37 UTC, zanac reviewed
so what i need to do for include officialy in hacs?

2023-12-04 15:38 UTC, ludeeus commented
You need to adjust your fork settings or create a PR from a different branch.

2024-09-03 07:59 UTC, closed without merging