Update theme
hacs/default pull request #2221
Opened 2023-12-10 19:52 UTC by Djelle

## Checklist

- [x ] I've read the [publishing documentation](https://hacs.xyz/docs/publish/start).
- [ x] I've added the [HACS action](https://hacs.xyz/docs/publish/action) to my repository.
- [ ] (For integrations only) I've added the [hassfest action](https://developers.home-assistant.io/blog/2020/04/16/hassfest/) to my repository.
- [ x] The actions are passing without any disabled checks in my repository.
- [ x] I've added a link to the action run on my repository below in the links section.
- [ x] I've created a new release of the repository after the validation actions were run successfully.

## Links

Link to current release: <https://github.com/Djelle/milcomarmy/releases/tag/v1.1>
Link to successful HACS action (without the `ignore` key): <https://github.com/Djelle/milcomarmy/actions/runs/7154501817>
Link to successful hassfest action (if integration): <>

2024-06-20 18:43 UTC, Djelle commented
Updated my theme to v2.0. Could not wait for review acceptance :) The submitted v1.1 is still there. Not sure what to do more. I hope my update doesn't mess with my pull request.
Cheers

2024-09-10 09:03 UTC, ludeeus commented on theme
> +  "Djelle/milcomarmy"
This list needs to be sorted.

2024-09-13 14:39 UTC, Djelle commented on theme
> +  "Djelle/milcomarmy"
Where do you find this code?

2024-09-19 19:53 UTC, Djelle commented on theme
> +  "Djelle/milcomarmy"
I think I figured out what to do.

2024-09-19 20:22 UTC, tjorim requested changes

2024-09-19 20:22 UTC, tjorim commented on theme
> +  "Djelle/milcomarmy"
```suggestion
  "Djelle/milcomarmy",
```

2024-09-19 20:22 UTC, tjorim commented on theme
> +  "wowgamr/animated-weather-card",
```suggestion
  "wowgamr/animated-weather-card"
```

2024-10-14 13:42 UTC, merged