Update integration with dobiss with IP
hacs/default pull request #2429
Opened 2024-03-27 17:59 UTC by avlemos

- [X] I've read the [publishing documentation](https://hacs.xyz/docs/publish/start).
- [X] I've added the [HACS action](https://hacs.xyz/docs/publish/action) to my repository.
- [X] (For integrations only) I've added the [hassfest action](https://developers.home-assistant.io/blog/2020/04/16/hassfest/) to my repository.
- [X] The actions are passing without any disabled checks in my repository.
- [X] I've added a link to the action run on my repository below in the links section.
- [X] I've created a new release of the repository after the validation actions were run successfully.

## Links

Link to current release: https://github.com/avlemos/dobiss/releases/tag/1.0.1
Link to successful HACS action (without the `ignore` key): https://github.com/avlemos/dobiss/actions/runs/8456355089
Link to successful hassfest action (if integration): https://github.com/avlemos/dobiss/actions/runs/8456355090

2025-01-06 13:17 UTC, ludeeus requested changes

2025-01-06 13:17 UTC, ludeeus commented on integration
> +  "avlemos/dobiss"
This list needs to be alphabetically sorted.

2025-01-06 14:37 UTC, avlemos commented on integration
> +  "avlemos/dobiss"
done! fixed the conflicting merge.

2025-01-09 07:05 UTC, ludeeus commented on integration
> +  "avlemos/dobiss",
There is no documentation here about what it does, to me it seems like you just took someone else's thing and repackaged it?

2025-01-09 07:54 UTC, avlemos commented on integration
> +  "avlemos/dobiss",
I forked the project [here](https://github.com/avlemos/HomeAssistantFiles), and have been working on it [here](https://github.com/avlemos/dobiss?tab=readme-ov-file), so it's easier to push to HACS.

the main reason for the fork, was that:

1. the author no longer maintains it, as they now have different hardware (I've communicated, and submitted some PRs to the original project. Two have them haven't been merged, and I don't think they ever will)
2. I was getting warnings from HA on deprecated structures/features
3. the original code would crash on my installation every 24 hours ([socket issues, corresponding PR on the original project](https://github.com/OpenJeDi/HomeAssistantFiles/pull/7))
4. not conveniently available through HACS

I've fixed these 4 things, and that is what I am trying to submit.

2025-01-16 08:02 UTC, ludeeus commented on integration
> +  "avlemos/dobiss",
There is _still_ no documentation about what your repository does.

2025-01-22 11:31 UTC, avlemos commented on integration
> +  "avlemos/dobiss",
ugh, of course. sorry about that.

I've updated the README file with some context, and will continue to work on it. Commit is here: https://github.com/avlemos/dobiss/commit/504857da51d211071846d92efdea6d796adea28d

2025-01-23 14:14 UTC, tjorim commented on integration
> +  "avlemos/dobiss",
@avlemos don't forget to make a new release with the updated readme.

2025-01-23 14:42 UTC, avlemos commented on integration
> +  "avlemos/dobiss",
yes, you can find it here: https://github.com/avlemos/dobiss/releases/tag/1.0.2 @tjorim

2025-01-30 07:00 UTC, merged