Adds new integration [cdnninja/yoto_ha]
hacs/default pull request #2478
Opened 2024-04-23 15:03 UTC by cdnninja

## Checklist

- [X] I've read the [publishing documentation](https://hacs.xyz/docs/publish/start).
- [X] I've added the [HACS action](https://hacs.xyz/docs/publish/action) to my repository.
- [X] (For integrations only) I've added the [hassfest action](https://developers.home-assistant.io/blog/2020/04/16/hassfest/) to my repository.
- [X] The actions are passing without any disabled checks in my repository.
- [X] I've added a link to the action run on my repository below in the links section.
- [X] I've created a new release of the repository after the validation actions were run successfully.

## Links

Link to current release: https://github.com/cdnninja/yoto_ha/releases/tag/v1.1.0
Link to successful HACS action (without the `ignore` key): https://github.com/cdnninja/yoto_ha/actions/runs/8802662472
Link to successful hassfest action (if integration): https://github.com/cdnninja/yoto_ha/actions/runs/8802662472

2024-12-10 22:44 UTC, cdnninja commented
I am seeing merging happening again so commenting that this one is still current.

2025-01-31 09:14 UTC, ludeeus requested changes

2025-01-31 09:14 UTC, ludeeus commented on integration
> +  "cdnninja/yoto_ha",
This list need to be sorted alphabetically.

2025-01-31 15:33 UTC, cdnninja commented on integration
> +  "cdnninja/yoto_ha",
Fixed.

2025-02-03 07:07 UTC, merged