Adds new integration [nexhome-org/nexhome-homeassistant-component]
hacs/default pull request #2521
Opened 2024-05-22 11:14 UTC by linzh322

## Checklist

- [x] I've read the [publishing documentation](https://hacs.xyz/docs/publish/start).
- [x] I've added the [HACS action](https://hacs.xyz/docs/publish/action) to my repository.
- [x] (For integrations only) I've added the [hassfest action](https://developers.home-assistant.io/blog/2020/04/16/hassfest/) to my repository.
- [x] The actions are passing without any disabled checks in my repository.
- [x] I've added a link to the action run on my repository below in the links section.
- [x] I've created a new release of the repository after the validation actions were run successfully.

## Links

Link to current release: <https://github.com/nexhome-org/nexhome-homeassistant-component/releases/tag/v1.1.8>
Link to successful HACS action (without the `ignore` key): <https://github.com/nexhome-org/nexhome-homeassistant-component/actions/runs/13672921086>
Link to successful hassfest action (if integration): <https://github.com/nexhome-org/nexhome-homeassistant-component/actions/runs/13672921103>

2025-02-11 08:46 UTC, ludeeus requested changes

2025-02-11 08:46 UTC, ludeeus commented on integration
> +  "nexhome-org/nexhome-homeassistant-component",
https://github.com/nexhome-org/nexhome-homeassistant-component/blob/v1.1.0/hacs.json#L5-L6  file does not exist <https://github.com/nexhome-org/nexhome-homeassistant-component/releases/tag/v1.1.0>

2025-02-17 01:39 UTC, linzh322 commented on integration
> +  "nexhome-org/nexhome-homeassistant-component",
hi,I have added nexhome.zip, please review it again, wish you a successful work
https://github.com/nexhome-org/nexhome-homeassistant-component/releases/tag/v1.1.0

2025-02-28 06:35 UTC, ludeeus commented on integration
> +  "nexhome-org/nexhome-homeassistant-component",
Do it properly with a github action, or don't do it at all.
This is not in the open spirit.

2025-03-03 08:09 UTC, linzh322 commented on integration
> +  "nexhome-org/nexhome-homeassistant-component",
I'm sorry about that, I've released a new version to fix it.

2025-03-03 15:00 UTC, ludeeus commented on integration
> +  "nexhome-org/nexhome-homeassistant-component",
I suggest you dont do asset at all, this is not how it  should be <https://github.com/nexhome-org/nexhome-homeassistant-component/actions/runs/13626062354/job/38083468371>
You are packing up the entire repo content.

2025-03-04 02:00 UTC, linzh322 commented on integration
> +  "nexhome-org/nexhome-homeassistant-component",
Half done is disappointing, I have limited the scope of packing, please review again, thank you!

2025-03-04 07:04 UTC, ludeeus commented on integration
> +  "nexhome-org/nexhome-homeassistant-component",
looks better.
However, <https://github.com/nexhome-org/nexhome-homeassistant-component/blob/main/hacs.json> is missing country notation.

2025-03-04 08:17 UTC, linzh322 commented on integration
> +  "nexhome-org/nexhome-homeassistant-component",
Ok, I've added the country key, but I see it's not required in the publish documentation🤔.
![image](https://github.com/user-attachments/assets/112bdd99-8182-4585-9d48-e5536225c87f)

2025-03-05 07:18 UTC, ludeeus commented on integration
> +  "nexhome-org/nexhome-homeassistant-component",
https://github.com/nexhome-org/nexhome-homeassistant-component/blob/v1.1.7/hacs.json
Not present in the current release.

It is required if it is only available for a selection of countries.

2025-03-05 09:46 UTC, linzh322 commented on integration
> +  "nexhome-org/nexhome-homeassistant-component",
I've released a new version.
In addition, I recommend adding this note to the documentation to prevent future developers from making mistakes.

2025-03-05 13:25 UTC, merged