Adds new integration [dreo-team/ha-dreo]
hacs/default pull request #2654
Opened 2024-08-20 07:36 UTC by dreo-team

Adds Dreo integration

## Checklist

- [x] I've read the [publishing documentation](https://hacs.xyz/docs/publish/start).
- [x] I've added the [HACS action](https://hacs.xyz/docs/publish/action) to my repository.
- [x] (For integrations only) I've added the [hassfest action](https://developers.home-assistant.io/blog/2020/04/16/hassfest/) to my repository.
- [x] The actions are passing without any disabled checks in my repository.
- [x] I've added a link to the action run on my repository below in the links section.
- [x] I've created a new release of the repository after the validation actions were run successfully.

## Links

Link to current release: <https://github.com/dreo-team/ha-dreo/releases/tag/v0.0.1>
Link to successful HACS action (without the `ignore` key): <https://github.com/dreo-team/ha-dreo/actions/runs/10362444444/job/28684434972>
Link to successful hassfest action (if integration): <https://github.com/dreo-team/ha-dreo/actions/runs/10362444444/job/28684434839>

2025-03-12 09:28 UTC, ludeeus commented on integration
> +  "dreo-team/ha-dreo",
This looks abandoned?
No movement since this was created.

2025-04-18 11:37 UTC, dreo-team commented on integration
> +  "dreo-team/ha-dreo",
Thanks for your attention!
This PR is not abandoned. I am still actively working on it, but progress has been slower than expected due to personal schedule and other priorities.
I plan to update this PR and fix existing issues in the near future. Your reminder is helpful and has motivated me to speed up the progress.
Thanks for your patience and support!

2025-04-18 11:56 UTC, dreo-team commented
![image](https://github.com/user-attachments/assets/c31f2b59-1f95-4b2e-b522-153f0da08a14)

integration File, Already exists"dreo-team/ha-dreo"

Thanks

2025-04-22 05:22 UTC, ludeeus commented on integration
> +  "dreo-team/ha-dreo",
This comment is not about this PR, it is about the linked repository in this PR, which even after that have had no movement.

2025-05-08 12:12 UTC, dreo-team commented
@ludeeus I have updated the repository name from dreo-team/ha-dreo to dreo-team/hacs-dreo to match the entry in the integration list. All code references and documentation have been updated accordingly. Could you please confirm if this resolves the previous issue? If there are any other problems that need to be addressed, please let me know. Thank you for your review.

2025-05-08 12:18 UTC, ludeeus requested changes

2025-05-08 12:18 UTC, ludeeus commented on integration
> +  "dreo-team/hacs-dreo",
Do not use "hacs" in the repository name.

2025-05-09 08:41 UTC, dreo-team commented on integration
> +  "dreo-team/hacs-dreo",
@ludeeus I've changed hacs-dreo to hass-dreoverse

2025-05-09 11:51 UTC, ludeeus commented
With 3 linters failing (sorted, hassfest, and HACS), and the repo being 1 week old, Im going to close this PR.
Create a new one when you are ready.

2025-05-09 11:51 UTC, closed without merging