Added new plugin SMHI Weather Warnings Card
hacs/default pull request #2763
Opened 2024-10-08 08:17 UTC by Nicxe

## Checklist

- [x ] I've read the [publishing documentation](https://hacs.xyz/docs/publish/start).
- [x ] I've added the [HACS action](https://hacs.xyz/docs/publish/action) to my repository.
- [ ] (For integrations only) I've added the [hassfest action](https://developers.home-assistant.io/blog/2020/04/16/hassfest/) to my repository.
- [x ] The actions are passing without any disabled checks in my repository.
- [x ] I've added a link to the action run on my repository below in the links section.
- [ x] I've created a new release of the repository after the validation actions were run successfully.

## Links

Link to current release: <https://github.com/Nicxe/home-assistant-smhialert-card/releases/tag/v1.1.0>
Link to successful HACS action (without the `ignore` key): <https://github.com/Nicxe/home-assistant-smhialert-card/actions/runs/11226125455>
Link to successful hassfest action (if integration): <>

2024-10-14 07:52 UTC, ludeeus requested changes

2024-10-14 07:52 UTC, ludeeus commented on integration
> +  "Nicxe/home-assistant-smhialerts",
Limit changes to 1 addition pr. PR.

2024-10-16 16:47 UTC, Nicxe commented on integration
> +  "Nicxe/home-assistant-smhialerts",
Removed the integration

2025-03-28 07:21 UTC, ludeeus commented on plugin
> +  "Nicxe/home-assistant-smhialert-card"
```suggestion
  "Nicxe/home-assistant-smhialert-card",
```

2025-04-10 05:21 UTC, ludeeus approved these changes

2025-04-10 05:21 UTC, merged