Adds new integration [Refoss/refoss-homeassistant]
hacs/default pull request #2795
Opened 2024-10-21 07:43 UTC by ashionky

## Checklist

- [x] I've read the [publishing documentation](https://hacs.xyz/docs/publish/start).
- [x] I've added the [HACS action](https://hacs.xyz/docs/publish/action) to my repository.
- [x] (For integrations only) I've added the [hassfest action](https://developers.home-assistant.io/blog/2020/04/16/hassfest/) to my repository.
- [x] The actions are passing without any disabled checks in my repository.
- [x] I've added a link to the action run on my repository below in the links section.
- [x] I've created a new release of the repository after the validation actions were run successfully.

## Links

Link to current release: <https://github.com/Refoss/refoss-homeassistant/releases/tag/v1.0.1>
Link to successful HACS action (without the `ignore` key): <https://github.com/Refoss/refoss-homeassistant/actions/runs/9574564790/job/26398003135>
Link to successful hassfest action (if integration): <https://github.com/Refoss/refoss-homeassistant/actions/runs/9574564790/job/26398003284>

2025-02-05 03:27 UTC, ashionky commented
<img width="824" alt="截屏2025-02-05 11 25 35" src="https://github.com/user-attachments/assets/7928b8df-1bb1-4a18-a07d-51c31b3ad8ab" />
<img width="931" alt="截屏2025-02-05 11 26 44" src="https://github.com/user-attachments/assets/ff3dec07-fa82-4334-82f1-e865757eee59" />

2025-04-14 09:30 UTC, ludeeus requested changes

2025-04-14 09:30 UTC, ludeeus commented on integration
> +  "Refoss/refoss-homeassistant",
PR is not editable by maintainers.

2025-04-14 09:51 UTC, ashionky commented on integration
> +  "Refoss/refoss-homeassistant",
Can't you edit the content here?

2025-04-14 09:52 UTC, ludeeus commented on integration
> +  "Refoss/refoss-homeassistant",
No, that is what "not editable by maintainers" mean.

2025-04-14 10:42 UTC, ashionky commented on integration
> +  "Refoss/refoss-homeassistant",
I am currently unable to set Allow edits from maintainers on this PR.
May I ask if I should resubmit a PR?

2025-04-14 10:44 UTC, ludeeus commented on integration
> +  "Refoss/refoss-homeassistant",
That or update the source tho be compliant.

2025-04-14 10:44 UTC, ludeeus commented on integration
> +  "Refoss/refoss-homeassistant",
Also, do not mark it as ready, unless it is ready.

2025-04-15 01:50 UTC, ashionky commented on integration
> +  "Refoss/refoss-homeassistant",
![image](https://github.com/user-attachments/assets/91710fa5-bc88-4760-aaa3-7399092f929e)
 Can you try it now。

2025-04-15 05:10 UTC, ludeeus commented on integration
> +  "Refoss/refoss-homeassistant",
I will not join your repository. Make it work as-is or re-create it with a fork on a non-org user.

2025-04-15 05:52 UTC, ashionky commented on integration
> +  "Refoss/refoss-homeassistant",
Thanks， I fork my personal account once.  Create a new PR     https://github.com/hacs/default/pull/3307

2025-04-16 07:33 UTC, ashionky commented on integration
> +  "Refoss/refoss-homeassistant",
@ludeeus Hi， Does the new PR meet the requirements?

2025-04-22 05:32 UTC, ludeeus commented on integration
> +  "Refoss/refoss-homeassistant",
yes. <img width="374" alt="2025-04-22_07-32-37" src="https://github.com/user-attachments/assets/efecfc66-aa2f-46e6-ac67-1953c31edaac" />

2025-04-22 05:32 UTC, closed without merging