Add mtrab/stromligning
hacs/default pull request #2816
Opened 2024-11-03 17:54 UTC by MTrab

## Checklist

- [x] I've read the [publishing documentation](https://hacs.xyz/docs/publish/start).
- [x] I've added the [HACS action](https://hacs.xyz/docs/publish/action) to my repository.
- [x] (For integrations only) I've added the [hassfest action](https://developers.home-assistant.io/blog/2020/04/16/hassfest/) to my repository.
- [x] The actions are passing without any disabled checks in my repository.
- [x] I've added a link to the action run on my repository below in the links section.
- [x] I've created a new release of the repository after the validation actions were run successfully.

## Links

Link to current release: <https://github.com/MTrab/stromligning/releases/tag/v0.1.0>
Link to successful HACS action (without the `ignore` key): <https://github.com/MTrab/stromligning/actions/runs/11647505890/job/32432838497>
Link to successful hassfest action (if integration): <https://github.com/MTrab/stromligning/actions/runs/11647505890/job/32432838588>

2025-04-15 07:57 UTC, ludeeus requested changes
This contains a submodule, which will **not** be accepted.

2025-04-15 09:51 UTC, MTrab commented
> This contains a submodule, which will **not** be accepted.

Which module?

2025-04-22 05:33 UTC, ludeeus commented
You are trying to add a submodule in this PR.

2025-04-22 07:47 UTC, MTrab commented
> You are trying to add a submodule in this PR.

It's an integration for electricity prices in Denmark 🤷‍♀️

2025-04-22 07:53 UTC, ludeeus commented
I am **not** talking about your repository, I am talking about this PR and the suggested changes in this PR against this repository.
Look at your changed files.

2025-04-22 09:14 UTC, MTrab commented
Oh - hadn't seen that :(

Should be fixed now.

2025-04-22 22:33 UTC, tjorim commented
Capitalization is not correct

2025-04-23 04:24 UTC, MTrab commented
> Capitalization is not correct

A hint?

2025-04-24 05:26 UTC, ludeeus approved these changes

2025-04-24 05:26 UTC, merged