Add homeassistant-myskoda
hacs/default pull request #2824
Opened 2024-11-06 10:00 UTC by WebSpider

Skoda is switching API's, for this reason we have rebuilt the integration.

`homeassistant-myskoda` will be developed moving forward.  We're adding it here, and after we have sunsetted `homeassistant-skodaconnect`, a PR will be made to remove it, allowing users to switch

## Checklist

- [X] I've read the [publishing documentation](https://hacs.xyz/docs/publish/start).
- [X] I've added the [HACS action](https://hacs.xyz/docs/publish/action) to my repository.
- [X] (For integrations only) I've added the [hassfest action](https://developers.home-assistant.io/blog/2020/04/16/hassfest/) to my repository.
- [X] The actions are passing without any disabled checks in my repository.
- [X] I've added a link to the action run on my repository below in the links section.
- [X] I've created a new release of the repository after the validation actions were run successfully.

## Links

Link to current release: https://github.com/skodaconnect/homeassistant-myskoda/releases/tag/v1.7.1
Link to successful HACS action (without the `ignore` key): https://github.com/skodaconnect/homeassistant-myskoda/actions/runs/11700759412/job/32585413910
Link to successful hassfest action (if integration): https://github.com/skodaconnect/homeassistant-myskoda/actions/runs/11700759412/job/32585413612

2025-04-16 07:26 UTC, ludeeus requested changes

2025-04-16 07:26 UTC, ludeeus commented on integration
> +  "zweckj/acaia"
You should not be adding `zweckj/acaia` here.

2025-05-03 09:35 UTC, WebSpider commented on integration
> +  "zweckj/acaia"
This must have been a leftover from a merge conflict. Ill fix this.

2025-05-07 05:12 UTC, ludeeus approved these changes

2025-05-07 05:14 UTC, merged