Add Radoff integration
hacs/default pull request #2909
Opened 2024-12-14 19:32 UTC by raelix

## Checklist

- [x] I've read the [publishing documentation](https://hacs.xyz/docs/publish/start).
- [x] I've added the [HACS action](https://hacs.xyz/docs/publish/action) to my repository.
- [x] (For integrations only) I've added the [hassfest action](https://developers.home-assistant.io/blog/2020/04/16/hassfest/) to my repository.
- [x] The actions are passing without any disabled checks in my repository.
- [x] I've added a link to the action run on my repository below in the links section.
- [x] I've created a new release of the repository after the validation actions were run successfully.

## Links

Link to current release: <https://github.com/raelix/HA-Radoff-integration/releases/tag/0.2.0>
Link to successful HACS action (without the `ignore` key): <https://github.com/raelix/HA-Radoff-integration/actions/runs/12332540842/job/34420481946>
Link to successful hassfest action (if integration): <https://github.com/raelix/HA-Radoff-integration/actions/runs/12332540842/job/34420482016>

2025-05-07 05:06 UTC, ludeeus requested changes

2025-05-07 05:06 UTC, ludeeus commented on integration
> +  "raelix/HA-Radoff-integration",
This list needs to be alphabetical.

2025-05-08 18:57 UTC, raelix commented on integration
> +  "raelix/HA-Radoff-integration",
Hi @ludeeus now should be good. Thanks!

2025-05-09 05:38 UTC, ludeeus approved these changes

2025-05-09 05:38 UTC, merged