Adds new integration [Home-Assistant-Custom-Component-Fortnite]
hacs/default pull request #617
Opened 2020-09-16 00:48 UTC by michaellunzer

2020-09-16 00:51 UTC, KTibow requested changes

2020-09-16 00:51 UTC, KTibow commented on integration
> +  "michaellunzer/Home-Assistant-Custom-Component-Fortnite"
```suggestion
  "michaellunzer/Home-Assistant-Custom-Component-Fortnite",
```

2020-09-16 01:11 UTC, KTibow requested changes

2020-09-16 01:11 UTC, KTibow commented on integration
> +  "michaellunzer/Home-Assistant-Custom-Component-Fortnite",
```suggestion
  "michaellunzer/Home-Assistant-Custom-Component-Fortnite",
  "Michsior14/ha-laser-egg",
```

2020-09-16 17:41 UTC, michaellunzer reviewed
looks good!

2020-09-16 17:44 UTC, michaellunzer commented
Hi @KTibow is there a way to re-run the validation checks on this PR? My pull requests in the brands and wheels repos have been approved and merged. Thanks!

2020-09-16 17:45 UTC, ludeeus commented
<https://hacs.xyz/docs/publish/include#re-run-checks>

2020-09-16 17:45 UTC, ludeeus commented
/recheck

2020-09-16 17:48 UTC, michaellunzer commented
> https://hacs.xyz/docs/publish/include#re-run-checks

thanks @ludeeus!

2020-09-16 19:23 UTC, UbhiTS approved these changes

2020-09-19 17:11 UTC, ludeeus commented
You should consider removing all `.DS_Store` files from your repo and push those, then add `.DS_Store` to  `.gitignore`

2020-09-19 17:12 UTC, merged