Add working samsungrac integration
hacs/default pull request #631
Opened 2020-09-25 13:31 UTC by atxbyea

2020-09-25 13:47 UTC, KTibow requested changes

2020-09-25 13:47 UTC, KTibow commented on integration
> +  "atxbyea/samsungrac",
```suggestion
  "atxbyea/samsungrac",
  "atymic/project_three_zero_ha",
```

2020-09-25 13:55 UTC, KTibow commented
/recheck

2020-09-25 16:07 UTC, KTibow commented
@atxbyea mind merging my `manifest.json` PR? Thanks!

2020-09-25 16:24 UTC, KTibow commented
/recheck

2020-09-25 16:40 UTC, KTibow commented
/recheck

2020-09-25 16:45 UTC, KTibow commented
@atxbyea what services does this register?

2020-09-28 07:54 UTC, atxbyea commented
/recheck

2020-10-01 11:16 UTC, atxbyea commented
/recheck

2020-10-02 15:51 UTC, atxbyea commented
/recheck

2020-10-03 09:51 UTC, ludeeus commented
/recheck

2020-10-05 08:58 UTC, atxbyea commented
@ludeeus @KTibow is this a bug in the check ?

`::INFO:: Category: integration
::INFO:: Repository: atxbyea/samsungrac
::INFO:: Found hacs.json
::INFO:: hacs.json is valid
Error:  ::error:: ::error:: The homeassistant key in manifest.json is no longer valid`

Says it opens hacs.json but mentions the issue is in manifest.json

According to https://hacs.xyz/docs/publish/start the minimum version supported should be "valid" albeit not "required"

2020-10-05 09:02 UTC, ludeeus commented
No, not a bug <https://github.com/atxbyea/samsungrac/blob/3.0/custom_components/climate_ip/manifest.json#L14>

2020-10-05 09:15 UTC, atxbyea commented
/recheck

2020-10-05 09:39 UTC, merged