Add Hifiberry integration
hacs/default pull request #638
Opened 2020-09-30 16:14 UTC by willholdoway

2020-09-30 16:38 UTC, KTibow requested changes

2020-09-30 16:38 UTC, KTibow commented on integration
>    "websylv/homeassistant-meteoswiss",
```suggestion
  "websylv/homeassistant-meteoswiss",
  "willholdoway/hifiberry",
```

2020-10-03 09:50 UTC, ludeeus commented
/recheck

2020-10-06 06:50 UTC, willholdoway commented
/recheck

2020-10-08 16:48 UTC, willholdoway commented
/recheck

2020-10-08 20:03 UTC, gilsonmandalogo approved these changes

2020-10-09 18:34 UTC, willholdoway commented
/recheck

2020-10-17 11:32 UTC, merged