Adds new plugin [marcomow/ble-bulb-card]
hacs/default pull request #687
Opened 2020-10-31 14:46 UTC by marcomow

2020-11-18 11:45 UTC, marcomow commented
Hi @ludeeus, as this is my first time ever issuing a pull request, I don't really understand what should I do to fix the faulty checks. Can you kindly tell me what should I work on?

2020-11-18 11:51 UTC, ludeeus requested changes

2020-11-18 11:51 UTC, ludeeus commented on plugin
> +  "marcomow/ble-bulb-card"
```suggestion
  "marcomow/ble-bulb-card",
```

Not valid JSON

2020-11-18 12:00 UTC, marcomow commented
/recheck

2020-11-20 08:39 UTC, marcomow commented
hi @ludeeus just checking out as this is my first pull request - am I missing anything?

2020-11-20 14:57 UTC, KTibow commented
@marcomow 
> DO NOT REQUEST REVIEWS, THAT IS JUST RUDE, IF YOU DO THE PULL REQUEST WILL BE CLOSED!

They just need to get around to it, also some people have different time zones you know.

2020-11-20 16:57 UTC, marcomow commented
@KTibow sorry, I didn't mean to be rude, I was genuinely asking as this is my first experience with a pull request.

2020-11-20 17:32 UTC, KTibow commented
It’s okay. It’s just that this is a tedious process, and not every PR can be reviewed.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

From: marcomow<mailto:notifications@github.com>
Sent: Friday, November 20, 2020 8:57 AM
To: hacs/default<mailto:default@noreply.github.com>
Cc: Kendell R<mailto:kendell.r@outlook.com>; Mention<mailto:mention@noreply.github.com>
Subject: Re: [hacs/default] Adds new plugin [marcomow/ble-bulb-card] (#687)


@KTibow<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FKTibow&data=04%7C01%7C%7Cc451ba9e135c4010862308d88d756849%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637414882679159720%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=iUzg6f78V5rHM6AoknfvWGVh0Juq2XvL5r2Gt6gJmSo%3D&reserved=0> sorry, I didn't mean to be rude, I was genuinely asking as this is my first experience with a pull request.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fhacs%2Fdefault%2Fpull%2F687%23issuecomment-731284858&data=04%7C01%7C%7Cc451ba9e135c4010862308d88d756849%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637414882679169720%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Qy%2F8ELSla%2BsiWRu2lFh%2FXDhmRN3Z4dt2qvzXKJnNOQg%3D&reserved=0>, or unsubscribe<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACR3DNUHRMZBHEAPF4UEZRDSQ2NYVANCNFSM4TF5VTXA&data=04%7C01%7C%7Cc451ba9e135c4010862308d88d756849%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637414882679179712%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=jSTHobTGaYLOWidVEeh4nJGUKHw%2FJJ4i0aCzARk%2BuRM%3D&reserved=0>.

2020-11-21 19:20 UTC, merged