Adds new integration [dwainscheeren/dwains-lovelace-dashboard]
hacs/default pull request #698
Opened 2020-11-15 11:31 UTC by dwainscheeren

Adds the loved Dwains Dashboard to HACS

2020-11-15 12:11 UTC, dwainscheeren commented
/recheck

2020-11-15 12:30 UTC, dwainscheeren commented
/recheck

2020-11-15 13:03 UTC, dwainscheeren commented
/recheck

2020-11-15 13:06 UTC, dwainscheeren commented
Not sure why it fails on "Check HACS" with `Error:  ::error:: No hacs.json file in the root of the repository.` but I got an `hacs.json` file in my repository.

2020-11-15 13:09 UTC, ludeeus commented
<https://github.com/dwainscheeren/dwains-lovelace-dashboard/tree/v1.4.1> Not in the current release which is what's beeing checked (and used when added)

2020-11-15 13:12 UTC, dwainscheeren commented
Okay from 2.0 release of my dashboard it will have it then so after I release 2.0 it will pass

2020-11-15 13:16 UTC, ludeeus commented
Yes

2020-11-15 13:26 UTC, Julien-Decoen commented
Yes please add it ! It would be very useful for all dwains-lovelace-dashboard' users ! 🙏

2020-11-16 12:55 UTC, XxCabbyoO commented
Cant wait :)

2020-11-16 19:31 UTC, dwainscheeren commented
/recheck

2021-01-17 12:29 UTC, dwainscheeren commented
/recheck

2021-01-17 12:33 UTC, dwainscheeren commented
@ludeeus What is the status on this? :)

2021-02-09 01:42 UTC, ludeeus requested changes
- Missing version <https://github.com/hacs/default/pull/698/checks?check_run_id=1859721752#step:2:359> 
- Missing brands icon <https://github.com/hacs/default/pull/698/checks?check_run_id=1859721752#step:2:362>
- Missing wheels <https://github.com/hacs/default/pull/698/checks?check_run_id=1859721752#step:2:369>

2021-03-13 14:55 UTC, ludeeus commented
Closing as stale

2021-03-13 14:55 UTC, closed without merging

2021-04-10 20:25 UTC, dwainscheeren commented
/recheck

2021-04-12 13:34 UTC, dwainscheeren commented
/recheck

2021-04-12 13:35 UTC, dwainscheeren commented
Please recheck @ludeeus