New Wattio Smart Home Integration Repo
hacs/default pull request #775
Opened 2021-01-11 12:28 UTC by dmoranf

2021-01-11 12:32 UTC, dmoranf commented
/recheck

2021-01-11 12:39 UTC, dmoranf commented
/recheck

2021-01-11 12:48 UTC, dmoranf commented
/recheck

2021-01-11 12:57 UTC, dmoranf commented
/recheck

2021-01-11 13:25 UTC, dmoranf commented
/recheck

2021-01-17 21:43 UTC, DCSBL approved these changes

2021-02-09 02:06 UTC, ludeeus requested changes
https://github.com/hacs/default/pull/775/checks?check_run_id=1857578364#step:2:203

2021-02-09 11:23 UTC, dmoranf commented
/recheck

2021-02-09 11:36 UTC, ludeeus approved these changes

2021-02-09 11:36 UTC, merged