add repository tholgir/TodoIst-Task-List
hacs/default pull request #782
Opened 2021-01-17 16:40 UTC by tholgir

This add a new plugin for displaying Todoist calender items

2021-01-19 07:12 UTC, jugla approved these changes

2021-01-28 04:00 UTC, jellespijker approved these changes

2021-02-08 18:27 UTC, ludeeus requested changes
Enable "Allow edits by maintainers" on the PR.

2021-02-08 19:53 UTC, tholgir commented
@ludeeus i enabled it

2021-02-08 20:00 UTC, merged