Add Veolia integration
hacs/default pull request #787
Opened 2021-01-22 20:49 UTC by tetienne

Thank you!

2021-01-23 10:26 UTC, jugla approved these changes

2021-01-28 22:10 UTC, jellespijker approved these changes

2021-02-09 01:57 UTC, ludeeus requested changes
https://github.com/hacs/default/pull/787/checks?check_run_id=1857847211#step:2:358

2021-02-13 21:00 UTC, tetienne commented
I've added the missing version key.

2021-02-14 18:40 UTC, ludeeus approved these changes

2021-02-14 18:40 UTC, merged