Adds new integration [myhomeiot/DahuaVTO]
hacs/default pull request #891
Opened 2021-04-04 18:52 UTC by myhomeiot

2021-04-09 10:18 UTC, NimlothPL approved these changes

2021-04-12 17:35 UTC, joffrey71 approved these changes
Working fine with VTO2202F-P.

2021-04-12 19:07 UTC, meteonet approved these changes

2021-04-12 20:08 UTC, Thoky81 approved these changes

2021-04-12 20:43 UTC, aalmarshad approved these changes

2021-04-12 20:55 UTC, vpnobregahome commented
Go

2021-04-14 09:35 UTC, NimlothPL approved these changes
Approved

2021-04-14 12:18 UTC, Mims455 approved these changes

2021-04-18 06:58 UTC, vkoloss approved these changes
worked for me

2021-04-25 08:59 UTC, aguilaair approved these changes
Working perfectly

2021-05-10 14:26 UTC, RichiTDI approved these changes

2021-05-13 10:49 UTC, ludeeus requested changes
CI does not pass

2021-05-14 00:21 UTC, myhomeiot commented
/recheck

2021-05-14 12:02 UTC, myhomeiot commented
> CI does not pass

Fixed.

2021-05-14 18:24 UTC, merged