Add integration STL
hacs/default pull request #892
Opened 2021-04-05 18:16 UTC by gjohansson-ST

Adding integration for STL - Svenska Trygghetslosningar

2021-05-05 23:12 UTC, PiotrMachowski approved these changes

2021-05-06 16:46 UTC, dreed47 approved these changes

2021-05-13 10:50 UTC, ludeeus requested changes
This should have the country key set in `hacs.json` https://hacs.xyz/docs/publish/start#hacsjson

2021-05-13 11:14 UTC, gjohansson-ST commented
> This should have the country key set in `hacs.json` https://hacs.xyz/docs/publish/start#hacsjson

Fair point. Now added

2021-05-13 11:16 UTC, ludeeus approved these changes

2021-05-13 11:17 UTC, merged