Add `moscow-pgu` extension to default
hacs/default pull request #893
Opened 2021-04-06 23:25 UTC by alryaz

(By the way, [https://hacs.xyz/docs/publish/start/include](https://hacs.xyz/docs/publish/start/include) leads to nowhere)

2021-04-06 23:30 UTC, alryaz commented
/recheck

2021-04-06 23:34 UTC, alryaz commented
/recheck

2021-05-06 16:43 UTC, dreed47 approved these changes

2021-05-13 10:55 UTC, ludeeus requested changes
CI does not pass

2021-06-22 01:30 UTC, closed without merging