Adds new integration [h4de5/home-assistant-vimar]
hacs/default pull request #944
Opened 2021-05-13 22:00 UTC by h4de5

2021-05-14 18:34 UTC, ludeeus requested changes
CI does not pass

2021-05-15 19:31 UTC, h4de5 commented
PR for images just got through

2021-05-15 21:03 UTC, gjohansson-ST commented
> PR for images just got through

Do a recheck

2021-05-15 22:51 UTC, h4de5 commented
/recheck

2021-05-18 10:58 UTC, h4de5 commented
/recheck

2021-06-12 19:30 UTC, merged