Add ipx800v4 and ecodevices integrations
hacs/default pull request #949
Opened 2021-05-14 17:31 UTC by Aohzan

Hello,

I add two of my custom integrations, ready to use :)

2021-05-14 18:06 UTC, ludeeus requested changes

2021-05-14 18:06 UTC, ludeeus commented on integration
> +  "Aohzan/ipx800",
You can only add one pr. PR.

2021-05-14 18:14 UTC, ludeeus requested changes
CI does not pass

2021-05-14 18:26 UTC, Aohzan commented
Wait for https://github.com/home-assistant/wheels-custom-integrations/pull/413

2021-05-17 14:35 UTC, Aohzan commented
/recheck

2021-06-12 18:11 UTC, ludeeus requested changes
CI does not pass
https://hacs.xyz/docs/publish/include/#before-submitting

2021-06-14 06:23 UTC, Aohzan commented
/recheck

2021-06-14 06:24 UTC, Aohzan commented
@ludeeus fixed, thanks

2021-06-21 09:25 UTC, ludeeus commented
marking this as draft for now as discussed on discord

2021-07-11 21:51 UTC, Aohzan commented
Hi @ludeeus 
last tag https://github.com/Aohzan/ipx800/releases/tag/2.4.0 add the authentication on the API call and a check on the host making the request. Tell me if it's OK or not like this

2021-08-15 11:30 UTC, ludeeus requested changes
CI does not pass
https://hacs.xyz/docs/publish/include/#before-submitting

2021-08-16 07:48 UTC, Aohzan commented
Fixed

2021-08-16 07:48 UTC, Aohzan commented
/recheck

2021-08-16 08:00 UTC, merged