Draft: Adds new integration [marcelwestrahome/home-assistant-niu-component]
hacs/default pull request #998
Opened 2021-06-20 09:18 UTC by syssi

2021-06-20 10:36 UTC, syssi commented
/recheck

2021-06-20 12:41 UTC, ludeeus requested changes
CI does not pass
https://hacs.xyz/docs/publish/include/#before-submitting

2021-06-20 13:18 UTC, syssi commented
Sorry for the noise. I will change the status of the PR as soon it''s ready and the build pass.

2021-06-22 17:14 UTC, syssi commented
/recheck

2021-06-22 17:27 UTC, syssi commented
The github action did pass. I hope this is ready to merge.

2021-08-15 11:00 UTC, merged